### ISSUE TITLE
networks文件夹里面缺少dacl.py文件，能上传一下吗？

### ISSUE THREAD

**Issue by fan196** [yaoing/DAN#10]
networks文件夹里面缺少dacl.py文件，能上传一下吗？

**Comment by yaoing** [comment]
OK, 更新了~

**Comment by fan196** [comment]
老哥您好，请问数据集方便分享嘛 做模式识别大作业要用到 给原作者发了邮件但是一直没有回复 
麻烦您了，仅用于论文实验，931251932@qq.com,有偿也可以，真的着急用。

**Comment by Dian-Yi** [comment]
> 老哥您好，请问数据集方便分享嘛 做模式识别大作业要用到 给原作者发了邮件但是一直没有回复 麻烦您了，仅用于论文实验，[931251932@qq.com](mailto:931251932@qq.com),有偿也可以，真的着急用。
老哥，有原始affect net数据集么

**Comment by yaoing** [comment]
抱歉~, 我得遵守申请协议

**Comment by Dian-Yi** [comment]
> 抱歉~, 我得遵守申请协议

老哥， pytorch和python版能说下么？

**Comment by yaoing** [comment]
pytorch==1.8 and python==3.8 ~
