### ISSUE TITLE
Trained cluster centers

### ISSUE THREAD

**Issue by amostayed** [yaoing/DAN#15]
Hi,
Is there any plan to also release the learned cluster centers of the FCN? One would think they are a part of the model. I understand they are not required for inference but may be handy for fine tuning if someone wants to use the affinity loss for fine tuning. 
Thanks.

**Comment by yaoing** [comment]
Hello, thanks for your suggest!
The FCN is one part of the whole end2end model and the  cluster centers  in FCN was trained with MAN and AFN synchronously. I mean that there are strong relevance among the sub-modules, and try to fine tuning the affinity loss individually may impact the performance of MAN, even the final result.

I don't know if I understood you correctly. And looking forward to your additions~

**Comment by amostayed** [comment]
Hi,
I am thinking about two different scenarios:
1. Say I am trying domain transfer with a different dataset but the same exact classes we have for AffectNet. In that case, I might want to just learn the FCN weights. To accomplish that I might try to minimize the affinity loss but with the cluster centers you already learned (and keep them fixed during the optimization). Or, I could fine-tune the entire model along with the cluster centers using all 3 losses. Either way, I could use those learned cluster centers in addition to the weights. 

2. I am doing transfer learning. Say I have a small dataset of some other types of facial expressions (say 5 classes and none of the expressions you trained on) and I would like to fine-tune your entire model (using all 3 losses simultaneously) with that data. Although in this case my labels are different from AffectNet, I would still prefer to initialize my cluster centers from the cluster centers you already learned. Now how to select the clusters is an entirely different and interesting problem. If you have any suggestion, please feel free.

**Comment by yaoing** [comment]
Hi,
It's an interesting problem, here are my ideas for these two scenarios:

1. For the same classes case, we can modify the forward method of class `DAN` to get the cluster center as:
```
def forward(self, x):
    x = self.features(x)
    ## take this discriminative feature map for some transfer learning tasks.

    return x
```
2. For a case with different classes, we could still use the AffectNet's cluster centers, and the code may same to case 1. Or we can copy the cluster centers indirectly by knowledge distillation.

For now, I can't guarantee the effectiveness of the transfer methods. And I am very glad to release the  learned cluster centers if it's really work to these scenarios.
