### ISSUE TITLE
A mistake in rafdb.py

### ISSUE THREAD

**Issue by RockPine520** [yaoing/DAN#16]
Hi,

In rafdb.py, line 235
`y_pred.append(targets.cpu().numpy())` should be
`y_pred.append(predicts.cpu().numpy())`

**Comment by RockPine520** [comment]
And 
`y_true = np.concatenate(y_true)`
`y_pred = np.concatenate(y_pred)`
should be added

**Comment by yaoing** [comment]
Thank you for the correction, I will update the codes!
