### ISSUE TITLE
How to get 82.75%

### ISSUE THREAD

**Issue by DXJ-Xiao** [yaoing/DAN#18]
Hello, can I ask you how Avg.Accuracy got here? Is it changed to 82.75 in the back?

**Comment by yaoing** [comment]
Thanks for your interest!

https://github.com/yaoing/DAN/blob/4253ad9f80131835e71ed4d7e703d0a6afb39431/rafdb.py#L250
As shown in the code, we calculate the balanced accuracy by sklean package. We change the correct value to 82.75 because a code mistake before.

**Comment by yaoing** [comment]
I will update the wrong result in my paper, thanks vary much!
