### ISSUE TITLE
Question about conversion of original Affectnet dataset

### ISSUE THREAD

**Issue by serendipitywgy** [yaoing/DAN#19]
Hello, how do I convert the original manually annotated Affectnet dataset I applied from the official website to the CSV format you provided?

**Comment by yaoing** [comment]
Thanks for your interest!
The csv file is same to the official annotation file, so we just need to put the `train_set` and `val_set` folder into `dataset\AfectNet`.

**Comment by serendipitywgy** [comment]
Thank you for your reply
