### ISSUE TITLE
Some questions about the dataset

### ISSUE THREAD

**Issue by VicZlq** [yaoing/DAN#20]
Thank you so much for your wonderful work! I'm now trying to reproduce the results, but I'm having some issues dividing the dataset. Are you using the AffectNet dataset, the 120G version or the 4G version? I am partitioning the data with some missing data.

**Comment by yaoing** [comment]
Thanks for your interest!
Our experiment use the 4G version of AffectNet. If it's miss match for dataset and our csv file, you can also load the dataset by this way:
https://github.com/yaoing/DAN/blob/4253ad9f80131835e71ed4d7e703d0a6afb39431/affectnet.py#L196

It will scan the npy annotation file from the dataset.

**Comment by VicZlq** [comment]
Thank you very much for your reply! I try to use dynamic loading, but the program will jump to line 160 and report an error.
    
def _get_labels(self, dataset):
        if isinstance(dataset, datasets.ImageFolder):
            return [x[1] for x in dataset.imgs]
        elif isinstance(dataset, torch.utils.data.Subset):
            return [dataset.dataset.imgs[i][1] for i in dataset.indices]
        else:
            raise NotImplementedError
Have you encountered similar problems?
