### ISSUE TITLE
Re-produce the result.

### ISSUE THREAD

**Issue by ltkhang** [yaoing/DAN#22]
Hi,

I was running your script rafdb.py with exact settings, however, I could only achieve 88.98 in accuracy.

Does your method depend on randomness?

![image](https://user-images.githubusercontent.com/4698213/164895449-9a59ba45-28e0-4d3e-913a-04ff13b49ae9.png)

**Comment by ltkhang** [comment]
The best I could get
![image](https://user-images.githubusercontent.com/4698213/164911078-cbf665e4-e493-44a5-b2c1-f1c681c31215.png)

**Comment by yaoing** [comment]
Thanks for your interest!
I did not set concrete random seed in the experimental code, so there are some fluctuations of accuracy values.

**Comment by ltkhang** [comment]
> Thanks for your interest! I did not set concrete random seed in the experimental code, so there are some fluctuations of accuracy values.

I actually would like to enhance your method but I can not find a correct setting to reach your academic reported result.

I need to retrain several times to reach above 89.0, most of the time it stuck at 89.98

Could you please provide a stable setting?

**Comment by ltkhang** [comment]
Besides, I also could not reproduce the result for Affectnet

![image](https://user-images.githubusercontent.com/4698213/166884336-82673f6c-1c30-4154-abcb-7d5f0a66c542.png)

**Comment by yaoing** [comment]
Sorry, I can't be of more help with this.
