### ISSUE TITLE
Grad Cam visualization 

### ISSUE THREAD

**Issue by Doanhdz** [yaoing/DAN#24]
First thanks for your great work? I have a question hope you can help me.
When I finished training model, I run run_grad_cam.py script and got very bad result. Attention module seem don't attent to important region
![Head0](https://drive.google.com/drive/u/0/folders/1JNC-ghy7B7fGFtpj7JU3_fAZzbCh9rYV)
![Head1](https://drive.google.com/drive/u/0/folders/1JNC-ghy7B7fGFtpj7JU3_fAZzbCh9rYV)
![Head2](https://drive.google.com/drive/u/0/folders/1JNC-ghy7B7fGFtpj7JU3_fAZzbCh9rYV)
![Head3](https://drive.google.com/drive/u/0/folders/1JNC-ghy7B7fGFtpj7JU3_fAZzbCh9rYV)

**Comment by yaoing** [comment]
Thans for your interest!
I would like to know what is the accuracy of the trained model, and the above pictures is lost.

**Comment by Doanhdz** [comment]
Thanks for your reply, i trained 3 class Positive(Happy), Neutral, Negative(Fear + Disgust + Angry), and accuracy is 80.06%
Here is the grad cam images
![head0_cam](https://user-images.githubusercontent.com/58201982/170820486-b03414d5-10a5-4252-9e23-ef2647d23eff.jpg)
![head1_cam](https://user-images.githubusercontent.com/58201982/170820489-ad71f625-5dc4-4e89-b96a-66b6d89d82bd.jpg)
![head2_cam](https://user-images.githubusercontent.com/58201982/170820492-667e7cdc-5e20-4f01-8e21-efdb0968d98d.jpg)
![head3_cam](https://user-images.githubusercontent.com/58201982/170820494-ed6aca21-0b89-4434-bca2-eba549094d8c.jpg)

**Comment by Doanhdz** [comment]
@yaoing Can you give me the answer ?

**Comment by yaoing** [comment]
Sorry, I have no idea about that.
