### ISSUE TITLE
Question in demo.py 

### ISSUE THREAD

**Issue by takis55** [yaoing/DAN#25]
First i think your  work is great.  I have a question hope you can help me.
When I run demo.py,  and i use an image it can detect one face and print one emotion label. 
How can it print all the faces in the image( f.e. 9 faces so 9 different emotions ) ? 
I try to input a for loop but i didnt see some results .

**Comment by yaoing** [comment]
Thanks for your interest!
You could replace the code of
https://github.com/yaoing/DAN/blob/408a47495c0a2c209d7345d352332b30f2608c78/demo.py#L55
and put your loop there.

Please check the facial detect results if it still not work.

**Comment by takis55** [comment]
thanks again.   I have another question , in most  of images i dont have problem and i have good result. In some images  it gives  me for index = 7 and  it shows me below code.  I cant find a solution to this. 
```
Traceback (most recent call last):

  File "c:\dan\dan-main\demo.py", line 182, in <module>
    label = model.fer(image)

  File "c:\dan\dan-main\demo.py", line 161, in fer
    label = self.labels[index]

IndexError: list index out of range
```
