### ISSUE TITLE
about Gad-CAM++ 

### ISSUE THREAD

**Issue by wooistxx** [yaoing/DAN#5]
impressive work, however, can you provide codes about how to visualization the attention map using grad-cam, we encounter some problems during reproducing it.

**Comment by yaoing** [comment]
Thanks for your interest, the grad-cam code has been uploaded, please check it out.

**Comment by wooistxx** [comment]
Thanks

**Comment by iAlexKai** [comment]
It seems that there is no ResNet18 in networks.dan, but you import that in run_grad_cam.py

**Comment by yaoing** [comment]
> 

It's my mistake, this visualization code import a experimental code out of the repository, you can replace the `ResNet18` with `DAN` class.
