### ISSUE TITLE
Number reproduce failed

### ISSUE THREAD

**Issue by jiaxiangshang** [yaoing/DAN#6]
Hi, really nice work.

But when I try to reproduce the number 89.7 in raf dataset.
I failed and only get the 89.0 result.

Can you give any ideas?

Thanks for your kind help,

**Comment by yaoing** [comment]
Thanks for your interest.
Without forcing the random seed, the reproduced results may have some fluctuations. This is a common phenomenon in FER tasks. And the 89.70 is not the best acc of our model. What you can do is try a few more times.
