### ISSUE TITLE
SFEW

### ISSUE THREAD

**Issue by toharl** [yaoing/DAN#7]
Thank you for your work.
Could you please share your training code for SFEW 2.0?

**Comment by yaoing** [comment]
Thanks for your interest !
We only make public for the codes of RAF-DB and AffectNet datasets. As for SFEW 2.0, the images need to be crop manually, and the different face detection model may lead in various result with our code.

**Comment by toharl** [comment]
May I know if you use the same transformations as in affectnet or raf-db? i.e: https://github.com/yaoing/DAN/blob/a46962ce2bc17d119e762a72d46815f02aaa128b/rafdb.py#L131

**Comment by yaoing** [comment]
Not really, It's the transfom function, you can make a referance:
```
data_transforms = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomApply([
            transforms.RandomAffine(20, scale=(0.8, 1), translate=(0.2, 0.2))
            ], p=0.5),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225]),
        ])
```

**Comment by toharl** [comment]
Thank you. May I know how do you crop and which face detection model you used in order to get your high performance?
