### ISSUE TITLE
train AffectNet and get best acc:0.6094. What did I do wrong?

### ISSUE THREAD

**Issue by Dian-Yi** [yaoing/DAN#9]
There is my settings,
bs                                       : 256
dataset_root_path              : /root/data/dataset/AffectNet_NEW/
lr                                         : 0.0001
num_class                           : 8
num_head                           : 4
num_workers                      : 24
rand_seed                           : 63079
save_path                           : checkpoint/train_DAN_ORIGN/63079
test_list                               : ['process_data/affectNet/AffectNet_Validation.list']
total_epoch                        : 40
train_list                              : ['process_data/affectNet/AffectNet_Train.list']
[Epoch 40] Training accuracy: 0.6057. Loss: 1.850. LR 0.000000
[Epoch 40] Validation accuracy:0.6036. Loss:1.867
best_acc:0.6094

The only code different is that I do not using datasets.ImageFolder to read data.
In your implementation details, i find that **"On RAF-DB and AffectNet datasets, we use the official aligned images samples directly."**.  I train Affectnet data using "Manually_Annotated" dir. 
I find that your affectnet.csv is different from mine on image file name and your affectnet.csv is preprocessed.
I test affecnet8_epoch5_acc0.6209.pth using my validation list, but get acc is 0.6039.  
so, What dataset are you using? how do you process affectnet?
What did I do wrong?

**Comment by Dian-Yi** [comment]
> Thanks for your interest! I think it's a dataset issue. The standard AffectNet already contains the cropped facial images and you don't need to do any extra manual annotation. The only thing you should do is to parse the label information.

thanks for your reply.
i find your train image name is ****.jpg affectnet.csv. Do you change the image name in making a csv file?  Do you use "Manually_Annotated" Folders data in AffectNet? or Can you share your orign validation.csv?

**Comment by yaoing** [comment]
The `affectnet.csv` file just for faster dataset loading, including the training and validation label info, I don't change the dataset. In fact, I also provide the orginal data loading method in the code, you can try this way to train the model.

**Comment by yaoing** [comment]
Did you download your dataset from the official address?

**Comment by Dian-Yi** [comment]
> Did you download your dataset from the official address?

No, I download from BaiduNetdisk. I don't find file name is '*_exp.npy'.

**Comment by yaoing** [comment]
I suggest you download it from the official website.

**Comment by Dian-Yi** [comment]
> I suggest you download it from the official website.

can you share your orign` validation.csv` to me for diffing, thanks very much

**Comment by yaoing** [comment]
Please check the column 2 from `affectnet.csv`, I have split the dataset with "train" and  "val" masks.

**Comment by Dian-Yi** [comment]
> Please check the column 2 from `affectnet.csv`, I have split the dataset with "train" and "val" masks.

i find that you rename the image file name, the csv file is different from downloading official website file.
